name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_DB: {{ cookiecutter.repo }}
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Install psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8 and black
      run: |
        make lint

    - name: Run migrations
      env:
        SECRET_KEY: test_key
        DATABASE_USER: test_user
        DATABASE_PASSWORD: test_password
      run: |
        python manage.py migrate

    - name: Test with pytest
      env:
        SECRET_KEY: test_key
        DATABASE_USER: test_user
        DATABASE_PASSWORD: test_password
      run: |
        make test
